# Generated by Django 3.0.7 on 2021-07-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_medidor', models.CharField(max_length=100)),
                ('marca_medidor', models.CharField(max_length=100)),
                ('modelo_medidor', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Desactivado')], default='Desactivado')),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_lectura', models.DateField()),
                ('horario_lectura', models.TimeField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SubEstacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Regional')),
            ],
        ),
        migrations.CreateModel(
            name='Transformador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('kva', models.IntegerField()),
                ('medidor', models.IntegerField()),
                ('alimentadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Alimentadora')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Regional')),
                ('sub_estaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.SubEstacion')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sumistro', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('alimentadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Alimentadora')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Empresa')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Regional')),
                ('sub_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.SubEstacion')),
                ('transformador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Transformador')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.IntegerField(blank=True, choices=[(1, 'SWITCH-SOLICITA'), (2, 'MEDIDOR-RESPUESTA')], null=True)),
                ('kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('operador', models.CharField(max_length=100)),
                ('error', models.IntegerField(blank=True, choices=[(1, 'OK'), (2, 'ERROR')], null=True)),
                ('observacion', models.CharField(max_length=250)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Medidor')),
            ],
        ),
        migrations.AddField(
            model_name='medidor',
            name='suministro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Suministro'),
        ),
        migrations.AddField(
            model_name='alimentadora',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Regional'),
        ),
        migrations.AddField(
            model_name='alimentadora',
            name='sub_estaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.SubEstacion'),
        ),
    ]
