# Generated by Django 3.0.7 on 2021-07-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_remove_suministro_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_medidor', models.CharField(max_length=100)),
                ('marca_mededor', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Desactivado')], default='Desactivado')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Suministro')),
            ],
        ),
    ]
