# Generated by Django 3.0.7 on 2021-07-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_registromedidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidor',
            name='modelo_mededor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
