# Generated by Django 3.0.7 on 2021-07-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_medidor_modelo_mededor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidor',
            old_name='marca_mededor',
            new_name='marca_medidor',
        ),
        migrations.RenameField(
            model_name='medidor',
            old_name='modelo_mededor',
            new_name='modelo_medidor',
        ),
    ]
