# Generated by Django 3.0.7 on 2021-07-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20210726_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromedidor',
            name='error',
            field=models.IntegerField(blank=True, choices=[(1, 'OK'), (2, 'ERROR')], null=True),
        ),
    ]
