# Generated by Django 3.0.7 on 2021-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='perfil',
            new_name='description',
        ),
    ]
